---
title: "CaltechAUTHORS Queue View"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE,message=FALSE, cache=FALSE)
```

Current contents in CaltechAUTHORS queue, listed by "@" tags present in the
comments. Submissions without "@" tags are listed as "new". This table
refreshes every hour during the workday. You can [manually refresh](https://github.com/caltechlibrary/irdm-queue-portal/actions/workflows/render.yaml) the table at GitHub. Last updated `r format(Sys.Date(), '%A, %B %d, %Y ')` `r format(Sys.time(), "%H:%M %Z")`

```{r data-table}
library(tidyverse)
library(DT)
events <- read_csv('queue.csv')
events <- transform(events, request = paste('<a href=https://authors.library.caltech.edu//communities/caltechauthors/requests/',request,'>',request,'</a>',sep=""))
events %>%
  datatable(escape = FALSE,
            rownames = FALSE, 
            colnames = c("Tag", "Updated Date", "Title", "Publisher","Groups","RDM ID", "Link"),
            class = "cell-border stripe", 
            filter = list(position = "top"),
            extensions = 'Buttons', options = list(dom = 'Bfrtip',
            buttons = c('colvis', 'csv', 'pdf'),pageLength = 50,
            order = list(list(0, 'desc'),list(1, 'desc')))
  )

```

