name: CodeMeta2CFF

on:
  push:
    tags:
      - v*    
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  CodeMeta2CFF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Convert CFF
        uses: caltechlibrary/codemeta2cff@main
      - name: Commit and Push Changes
        id: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Add CITATION.cff for release'
          file_pattern: 'CITATION.cff'
