on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

name: Render site

jobs:
  render:
    name: Render site
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ames
      - name: Update data
        run: |
          python get_queue.py
      - name: Commit results
        run: |
          git commit queue.csv -m 'Re-build index.html' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("tidyverse")'
      - name: Install DT
        run: Rscript -e 'install.packages("DT")'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("index.Rmd")'
      - name: Commit results
        run: |
          git commit index.html -m 'Re-build index.html' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
